export const SHOW_ALL_FILMS = 'SHOW_ALL_FILMS'
export const SHOW_FILM_BY_ID = 'SHOW_FILM_BY_ID'
export const SHOW_FILM_BY_SEARCH = 'SHOW_FILM_BY_SEARCH'

export const COUNT_PEOPLES = 'COUNT_PEOPLES'
export const NEXT_PEOPLES = 'NEXT_PEOPLES'
export const PREVIOUS_PEOPLES = 'PREVIOUS_PEOPLES'
export const SHOW_ALL_PEOPLES = 'SHOW_ALL_PEOPLES'
export const SHOW_PEOPLE_BY_ID = 'SHOW_PEOPLE_BY_ID'
export const SHOW_PEOPLE_BY_SEARCH = 'SHOW_PEOPLE_BY_SEARCH'

export const COUNT_PLANETS = 'COUNT_PLANETS'
export const NEXT_PLANETS = 'NEXT_PLANETS'
export const PREVIOUS_PLANETS = 'PREVIOUS_PLANETS'
export const SHOW_ALL_PLANETS = 'SHOW_ALL_PLANETS'
export const SHOW_PLANET_BY_ID = 'SHOW_PLANET_BY_ID'
export const SHOW_PLANET_BY_SEARCH = 'SHOW_PLANET_BY_SEARCH'

export const SHOW_ALL_SPECIES = 'SHOW_ALL_SPECIES'
export const SHOW_SPECIES_BY_ID = 'SHOW_SPECIES_BY_ID'
export const SHOW_SPECIES_BY_SEARCH = 'SHOW_SPECIES_BY_SEARCH'

export const SHOW_ALL_STARSHIPS = 'SHOW_ALL_STARSHIPS'
export const SHOW_STARSHIP_BY_ID = 'SHOW_STARSHIP_BY_ID'
export const SHOW_STARSHIP_BY_SEARCH = 'SHOW_STARSHIP_BY_SEARCH'

export const SHOW_ALL_VEHICLES = 'SHOW_ALL_VEHICLES'
export const SHOW_VEHICLE_BY_ID = 'SHOW_VEHICLE_BY_ID'
export const SHOW_VEHICLE_BY_SEARCH = 'SHOW_VEHICLE_BY_SEARCH'